apiVersion: v1
kind: Service
metadata:
  name: axon-admin-api
  namespace: axon-admin
  labels:
    app: axon-admin-api
spec:
  selector:
    app: axon-admin-api
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
